#!/bin/bash

cd ${1:-.}

while IFS= read -r row; do
	rm -rf "/service/files/$row"
done < <(sqlite3 db.sqlite "SELECT auth FROM users WHERE creat < strftime('%s', 'now') - 600")

sqlite3 db.sqlite "DELETE FROM users WHERE creat < strftime('%s', 'now') - 600"

