#!/bin/bash

while IFS= read -r row; do
	path=$(realpath "/service/files/$row")
	if [[ "$(dirname "$path")" -ef "/service/files" ]]; then
		rm -rf "$path"
	fi
done < <(sqlite3 /service/db.sqlite \
	"SELECT dir FROM files WHERE creat < strftime('%s', 'now') - 10")

while IFS= read -r row; do
	path=$(realpath "/service/reports/$row")
	if [ "$(dirname "$path")" -ef "/service/reports" ]; then
		rm -rf "$path"
	fi
done < <(sqlite3 /service/db.sqlite \
	"SELECT file FROM reports WHERE creat < strftime('%s', 'now') - 10")

sqlite3 /service/db.sqlite "PRAGMA foreign_keys = ON; \
	DELETE FROM users WHERE creat < strftime('%s', 'now') - 10"

