version: '2.1'
services:
  catchbox-checker:
    build: .
    ports:
      - 9091:9091
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=catchbox-mongo
      - MONGO_PORT=27017
      - MONGO_USER=catchbox_checker
      - MONGO_PASSWORD=catchbox_checker
  catchbox-mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: catchbox_checker
      MONGO_INITDB_ROOT_PASSWORD: catchbox_checker
