version: '2.1'
services:
  catchbox-checker:
    build: .
    ports:
      - 9092:9092
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=catchbox-mongo
      - MONGO_PORT=9093
      - MONGO_USER=catchbox_checker
      - MONGO_PASSWORD=catchbox_checker
  catchbox-mongo:
    image: mongo
    command: mongod --port 9093
    volumes:
      - ./data:/data/db
    ports:
      - 9093:9093
    environment:
      MONGO_INITDB_ROOT_USERNAME: catchbox_checker
      MONGO_INITDB_ROOT_PASSWORD: catchbox_checker
